// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: casia/isiteam/videosearch/protocol/requestProto.proto

package casia.isiteam.videosearch.protocol;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code casia.isiteam.videosearch.protocol.MethodType}
   */
  public enum MethodType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADD_VIDEO = 1;</code>
     */
    ADD_VIDEO(0, 1),
    /**
     * <code>SEARCH_VIDEO = 2;</code>
     */
    SEARCH_VIDEO(1, 2),
    /**
     * <code>DELETE_VIDEO = 3;</code>
     */
    DELETE_VIDEO(2, 3),
    ;

    /**
     * <code>ADD_VIDEO = 1;</code>
     */
    public static final int ADD_VIDEO_VALUE = 1;
    /**
     * <code>SEARCH_VIDEO = 2;</code>
     */
    public static final int SEARCH_VIDEO_VALUE = 2;
    /**
     * <code>DELETE_VIDEO = 3;</code>
     */
    public static final int DELETE_VIDEO_VALUE = 3;


    public final int getNumber() { return value; }

    public static MethodType valueOf(int value) {
      switch (value) {
        case 1: return ADD_VIDEO;
        case 2: return SEARCH_VIDEO;
        case 3: return DELETE_VIDEO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MethodType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MethodType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MethodType>() {
            public MethodType findValueByNumber(int number) {
              return MethodType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return casia.isiteam.videosearch.protocol.RequestProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MethodType[] VALUES = values();

    public static MethodType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MethodType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:casia.isiteam.videosearch.protocol.MethodType)
  }

  public interface HeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:casia.isiteam.videosearch.protocol.Head)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .casia.isiteam.videosearch.protocol.MethodType methodType = 1;</code>
     */
    boolean hasMethodType();
    /**
     * <code>required .casia.isiteam.videosearch.protocol.MethodType methodType = 1;</code>
     */
    casia.isiteam.videosearch.protocol.RequestProto.MethodType getMethodType();
  }
  /**
   * Protobuf type {@code casia.isiteam.videosearch.protocol.Head}
   */
  public static final class Head extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:casia.isiteam.videosearch.protocol.Head)
      HeadOrBuilder {
    // Use Head.newBuilder() to construct.
    private Head(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Head(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Head defaultInstance;
    public static Head getDefaultInstance() {
      return defaultInstance;
    }

    public Head getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Head(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              casia.isiteam.videosearch.protocol.RequestProto.MethodType value = casia.isiteam.videosearch.protocol.RequestProto.MethodType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                methodType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Head_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Head_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              casia.isiteam.videosearch.protocol.RequestProto.Head.class, casia.isiteam.videosearch.protocol.RequestProto.Head.Builder.class);
    }

    public static com.google.protobuf.Parser<Head> PARSER =
        new com.google.protobuf.AbstractParser<Head>() {
      public Head parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Head(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Head> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int METHODTYPE_FIELD_NUMBER = 1;
    private casia.isiteam.videosearch.protocol.RequestProto.MethodType methodType_;
    /**
     * <code>required .casia.isiteam.videosearch.protocol.MethodType methodType = 1;</code>
     */
    public boolean hasMethodType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .casia.isiteam.videosearch.protocol.MethodType methodType = 1;</code>
     */
    public casia.isiteam.videosearch.protocol.RequestProto.MethodType getMethodType() {
      return methodType_;
    }

    private void initFields() {
      methodType_ = casia.isiteam.videosearch.protocol.RequestProto.MethodType.ADD_VIDEO;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMethodType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, methodType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, methodType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static casia.isiteam.videosearch.protocol.RequestProto.Head parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Head parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Head parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Head parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Head parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Head parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Head parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Head parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Head parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Head parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(casia.isiteam.videosearch.protocol.RequestProto.Head prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code casia.isiteam.videosearch.protocol.Head}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:casia.isiteam.videosearch.protocol.Head)
        casia.isiteam.videosearch.protocol.RequestProto.HeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Head_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Head_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                casia.isiteam.videosearch.protocol.RequestProto.Head.class, casia.isiteam.videosearch.protocol.RequestProto.Head.Builder.class);
      }

      // Construct using casia.isiteam.videosearch.protocol.RequestProto.Head.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        methodType_ = casia.isiteam.videosearch.protocol.RequestProto.MethodType.ADD_VIDEO;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Head_descriptor;
      }

      public casia.isiteam.videosearch.protocol.RequestProto.Head getDefaultInstanceForType() {
        return casia.isiteam.videosearch.protocol.RequestProto.Head.getDefaultInstance();
      }

      public casia.isiteam.videosearch.protocol.RequestProto.Head build() {
        casia.isiteam.videosearch.protocol.RequestProto.Head result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public casia.isiteam.videosearch.protocol.RequestProto.Head buildPartial() {
        casia.isiteam.videosearch.protocol.RequestProto.Head result = new casia.isiteam.videosearch.protocol.RequestProto.Head(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.methodType_ = methodType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof casia.isiteam.videosearch.protocol.RequestProto.Head) {
          return mergeFrom((casia.isiteam.videosearch.protocol.RequestProto.Head)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(casia.isiteam.videosearch.protocol.RequestProto.Head other) {
        if (other == casia.isiteam.videosearch.protocol.RequestProto.Head.getDefaultInstance()) return this;
        if (other.hasMethodType()) {
          setMethodType(other.getMethodType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMethodType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        casia.isiteam.videosearch.protocol.RequestProto.Head parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (casia.isiteam.videosearch.protocol.RequestProto.Head) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private casia.isiteam.videosearch.protocol.RequestProto.MethodType methodType_ = casia.isiteam.videosearch.protocol.RequestProto.MethodType.ADD_VIDEO;
      /**
       * <code>required .casia.isiteam.videosearch.protocol.MethodType methodType = 1;</code>
       */
      public boolean hasMethodType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.MethodType methodType = 1;</code>
       */
      public casia.isiteam.videosearch.protocol.RequestProto.MethodType getMethodType() {
        return methodType_;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.MethodType methodType = 1;</code>
       */
      public Builder setMethodType(casia.isiteam.videosearch.protocol.RequestProto.MethodType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        methodType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.MethodType methodType = 1;</code>
       */
      public Builder clearMethodType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        methodType_ = casia.isiteam.videosearch.protocol.RequestProto.MethodType.ADD_VIDEO;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:casia.isiteam.videosearch.protocol.Head)
    }

    static {
      defaultInstance = new Head(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:casia.isiteam.videosearch.protocol.Head)
  }

  public interface ContextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:casia.isiteam.videosearch.protocol.Context)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string context = 1;</code>
     */
    boolean hasContext();
    /**
     * <code>required string context = 1;</code>
     */
    java.lang.String getContext();
    /**
     * <code>required string context = 1;</code>
     */
    com.google.protobuf.ByteString
        getContextBytes();
  }
  /**
   * Protobuf type {@code casia.isiteam.videosearch.protocol.Context}
   */
  public static final class Context extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:casia.isiteam.videosearch.protocol.Context)
      ContextOrBuilder {
    // Use Context.newBuilder() to construct.
    private Context(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Context(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Context defaultInstance;
    public static Context getDefaultInstance() {
      return defaultInstance;
    }

    public Context getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Context(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              context_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Context_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Context_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              casia.isiteam.videosearch.protocol.RequestProto.Context.class, casia.isiteam.videosearch.protocol.RequestProto.Context.Builder.class);
    }

    public static com.google.protobuf.Parser<Context> PARSER =
        new com.google.protobuf.AbstractParser<Context>() {
      public Context parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Context(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Context> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CONTEXT_FIELD_NUMBER = 1;
    private java.lang.Object context_;
    /**
     * <code>required string context = 1;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string context = 1;</code>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string context = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      context_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static casia.isiteam.videosearch.protocol.RequestProto.Context parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Context parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Context parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Context parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Context parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Context parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Context parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Context parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Context parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Context parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(casia.isiteam.videosearch.protocol.RequestProto.Context prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code casia.isiteam.videosearch.protocol.Context}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:casia.isiteam.videosearch.protocol.Context)
        casia.isiteam.videosearch.protocol.RequestProto.ContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Context_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Context_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                casia.isiteam.videosearch.protocol.RequestProto.Context.class, casia.isiteam.videosearch.protocol.RequestProto.Context.Builder.class);
      }

      // Construct using casia.isiteam.videosearch.protocol.RequestProto.Context.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Context_descriptor;
      }

      public casia.isiteam.videosearch.protocol.RequestProto.Context getDefaultInstanceForType() {
        return casia.isiteam.videosearch.protocol.RequestProto.Context.getDefaultInstance();
      }

      public casia.isiteam.videosearch.protocol.RequestProto.Context build() {
        casia.isiteam.videosearch.protocol.RequestProto.Context result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public casia.isiteam.videosearch.protocol.RequestProto.Context buildPartial() {
        casia.isiteam.videosearch.protocol.RequestProto.Context result = new casia.isiteam.videosearch.protocol.RequestProto.Context(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.context_ = context_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof casia.isiteam.videosearch.protocol.RequestProto.Context) {
          return mergeFrom((casia.isiteam.videosearch.protocol.RequestProto.Context)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(casia.isiteam.videosearch.protocol.RequestProto.Context other) {
        if (other == casia.isiteam.videosearch.protocol.RequestProto.Context.getDefaultInstance()) return this;
        if (other.hasContext()) {
          bitField0_ |= 0x00000001;
          context_ = other.context_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContext()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        casia.isiteam.videosearch.protocol.RequestProto.Context parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (casia.isiteam.videosearch.protocol.RequestProto.Context) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object context_ = "";
      /**
       * <code>required string context = 1;</code>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string context = 1;</code>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            context_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder setContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:casia.isiteam.videosearch.protocol.Context)
    }

    static {
      defaultInstance = new Context(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:casia.isiteam.videosearch.protocol.Context)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:casia.isiteam.videosearch.protocol.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    boolean hasHead();
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    casia.isiteam.videosearch.protocol.RequestProto.Head getHead();
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    casia.isiteam.videosearch.protocol.RequestProto.HeadOrBuilder getHeadOrBuilder();

    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    boolean hasContext();
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    casia.isiteam.videosearch.protocol.RequestProto.Context getContext();
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    casia.isiteam.videosearch.protocol.RequestProto.ContextOrBuilder getContextOrBuilder();
  }
  /**
   * Protobuf type {@code casia.isiteam.videosearch.protocol.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:casia.isiteam.videosearch.protocol.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              casia.isiteam.videosearch.protocol.RequestProto.Head.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = head_.toBuilder();
              }
              head_ = input.readMessage(casia.isiteam.videosearch.protocol.RequestProto.Head.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(head_);
                head_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              casia.isiteam.videosearch.protocol.RequestProto.Context.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = context_.toBuilder();
              }
              context_ = input.readMessage(casia.isiteam.videosearch.protocol.RequestProto.Context.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(context_);
                context_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              casia.isiteam.videosearch.protocol.RequestProto.Request.class, casia.isiteam.videosearch.protocol.RequestProto.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEAD_FIELD_NUMBER = 1;
    private casia.isiteam.videosearch.protocol.RequestProto.Head head_;
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    public boolean hasHead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    public casia.isiteam.videosearch.protocol.RequestProto.Head getHead() {
      return head_;
    }
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    public casia.isiteam.videosearch.protocol.RequestProto.HeadOrBuilder getHeadOrBuilder() {
      return head_;
    }

    public static final int CONTEXT_FIELD_NUMBER = 2;
    private casia.isiteam.videosearch.protocol.RequestProto.Context context_;
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    public casia.isiteam.videosearch.protocol.RequestProto.Context getContext() {
      return context_;
    }
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    public casia.isiteam.videosearch.protocol.RequestProto.ContextOrBuilder getContextOrBuilder() {
      return context_;
    }

    private void initFields() {
      head_ = casia.isiteam.videosearch.protocol.RequestProto.Head.getDefaultInstance();
      context_ = casia.isiteam.videosearch.protocol.RequestProto.Context.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHead().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getContext().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, context_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, context_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static casia.isiteam.videosearch.protocol.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(casia.isiteam.videosearch.protocol.RequestProto.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code casia.isiteam.videosearch.protocol.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:casia.isiteam.videosearch.protocol.Request)
        casia.isiteam.videosearch.protocol.RequestProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                casia.isiteam.videosearch.protocol.RequestProto.Request.class, casia.isiteam.videosearch.protocol.RequestProto.Request.Builder.class);
      }

      // Construct using casia.isiteam.videosearch.protocol.RequestProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeadFieldBuilder();
          getContextFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headBuilder_ == null) {
          head_ = casia.isiteam.videosearch.protocol.RequestProto.Head.getDefaultInstance();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (contextBuilder_ == null) {
          context_ = casia.isiteam.videosearch.protocol.RequestProto.Context.getDefaultInstance();
        } else {
          contextBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return casia.isiteam.videosearch.protocol.RequestProto.internal_static_casia_isiteam_videosearch_protocol_Request_descriptor;
      }

      public casia.isiteam.videosearch.protocol.RequestProto.Request getDefaultInstanceForType() {
        return casia.isiteam.videosearch.protocol.RequestProto.Request.getDefaultInstance();
      }

      public casia.isiteam.videosearch.protocol.RequestProto.Request build() {
        casia.isiteam.videosearch.protocol.RequestProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public casia.isiteam.videosearch.protocol.RequestProto.Request buildPartial() {
        casia.isiteam.videosearch.protocol.RequestProto.Request result = new casia.isiteam.videosearch.protocol.RequestProto.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headBuilder_ == null) {
          result.head_ = head_;
        } else {
          result.head_ = headBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (contextBuilder_ == null) {
          result.context_ = context_;
        } else {
          result.context_ = contextBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof casia.isiteam.videosearch.protocol.RequestProto.Request) {
          return mergeFrom((casia.isiteam.videosearch.protocol.RequestProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(casia.isiteam.videosearch.protocol.RequestProto.Request other) {
        if (other == casia.isiteam.videosearch.protocol.RequestProto.Request.getDefaultInstance()) return this;
        if (other.hasHead()) {
          mergeHead(other.getHead());
        }
        if (other.hasContext()) {
          mergeContext(other.getContext());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHead()) {
          
          return false;
        }
        if (!hasContext()) {
          
          return false;
        }
        if (!getHead().isInitialized()) {
          
          return false;
        }
        if (!getContext().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        casia.isiteam.videosearch.protocol.RequestProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (casia.isiteam.videosearch.protocol.RequestProto.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private casia.isiteam.videosearch.protocol.RequestProto.Head head_ = casia.isiteam.videosearch.protocol.RequestProto.Head.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          casia.isiteam.videosearch.protocol.RequestProto.Head, casia.isiteam.videosearch.protocol.RequestProto.Head.Builder, casia.isiteam.videosearch.protocol.RequestProto.HeadOrBuilder> headBuilder_;
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public boolean hasHead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public casia.isiteam.videosearch.protocol.RequestProto.Head getHead() {
        if (headBuilder_ == null) {
          return head_;
        } else {
          return headBuilder_.getMessage();
        }
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public Builder setHead(casia.isiteam.videosearch.protocol.RequestProto.Head value) {
        if (headBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          head_ = value;
          onChanged();
        } else {
          headBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public Builder setHead(
          casia.isiteam.videosearch.protocol.RequestProto.Head.Builder builderForValue) {
        if (headBuilder_ == null) {
          head_ = builderForValue.build();
          onChanged();
        } else {
          headBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public Builder mergeHead(casia.isiteam.videosearch.protocol.RequestProto.Head value) {
        if (headBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              head_ != casia.isiteam.videosearch.protocol.RequestProto.Head.getDefaultInstance()) {
            head_ =
              casia.isiteam.videosearch.protocol.RequestProto.Head.newBuilder(head_).mergeFrom(value).buildPartial();
          } else {
            head_ = value;
          }
          onChanged();
        } else {
          headBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public Builder clearHead() {
        if (headBuilder_ == null) {
          head_ = casia.isiteam.videosearch.protocol.RequestProto.Head.getDefaultInstance();
          onChanged();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public casia.isiteam.videosearch.protocol.RequestProto.Head.Builder getHeadBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeadFieldBuilder().getBuilder();
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public casia.isiteam.videosearch.protocol.RequestProto.HeadOrBuilder getHeadOrBuilder() {
        if (headBuilder_ != null) {
          return headBuilder_.getMessageOrBuilder();
        } else {
          return head_;
        }
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          casia.isiteam.videosearch.protocol.RequestProto.Head, casia.isiteam.videosearch.protocol.RequestProto.Head.Builder, casia.isiteam.videosearch.protocol.RequestProto.HeadOrBuilder> 
          getHeadFieldBuilder() {
        if (headBuilder_ == null) {
          headBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              casia.isiteam.videosearch.protocol.RequestProto.Head, casia.isiteam.videosearch.protocol.RequestProto.Head.Builder, casia.isiteam.videosearch.protocol.RequestProto.HeadOrBuilder>(
                  getHead(),
                  getParentForChildren(),
                  isClean());
          head_ = null;
        }
        return headBuilder_;
      }

      private casia.isiteam.videosearch.protocol.RequestProto.Context context_ = casia.isiteam.videosearch.protocol.RequestProto.Context.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          casia.isiteam.videosearch.protocol.RequestProto.Context, casia.isiteam.videosearch.protocol.RequestProto.Context.Builder, casia.isiteam.videosearch.protocol.RequestProto.ContextOrBuilder> contextBuilder_;
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public casia.isiteam.videosearch.protocol.RequestProto.Context getContext() {
        if (contextBuilder_ == null) {
          return context_;
        } else {
          return contextBuilder_.getMessage();
        }
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public Builder setContext(casia.isiteam.videosearch.protocol.RequestProto.Context value) {
        if (contextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          context_ = value;
          onChanged();
        } else {
          contextBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public Builder setContext(
          casia.isiteam.videosearch.protocol.RequestProto.Context.Builder builderForValue) {
        if (contextBuilder_ == null) {
          context_ = builderForValue.build();
          onChanged();
        } else {
          contextBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public Builder mergeContext(casia.isiteam.videosearch.protocol.RequestProto.Context value) {
        if (contextBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              context_ != casia.isiteam.videosearch.protocol.RequestProto.Context.getDefaultInstance()) {
            context_ =
              casia.isiteam.videosearch.protocol.RequestProto.Context.newBuilder(context_).mergeFrom(value).buildPartial();
          } else {
            context_ = value;
          }
          onChanged();
        } else {
          contextBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public Builder clearContext() {
        if (contextBuilder_ == null) {
          context_ = casia.isiteam.videosearch.protocol.RequestProto.Context.getDefaultInstance();
          onChanged();
        } else {
          contextBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public casia.isiteam.videosearch.protocol.RequestProto.Context.Builder getContextBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getContextFieldBuilder().getBuilder();
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public casia.isiteam.videosearch.protocol.RequestProto.ContextOrBuilder getContextOrBuilder() {
        if (contextBuilder_ != null) {
          return contextBuilder_.getMessageOrBuilder();
        } else {
          return context_;
        }
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          casia.isiteam.videosearch.protocol.RequestProto.Context, casia.isiteam.videosearch.protocol.RequestProto.Context.Builder, casia.isiteam.videosearch.protocol.RequestProto.ContextOrBuilder> 
          getContextFieldBuilder() {
        if (contextBuilder_ == null) {
          contextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              casia.isiteam.videosearch.protocol.RequestProto.Context, casia.isiteam.videosearch.protocol.RequestProto.Context.Builder, casia.isiteam.videosearch.protocol.RequestProto.ContextOrBuilder>(
                  getContext(),
                  getParentForChildren(),
                  isClean());
          context_ = null;
        }
        return contextBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:casia.isiteam.videosearch.protocol.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:casia.isiteam.videosearch.protocol.Request)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_casia_isiteam_videosearch_protocol_Head_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_casia_isiteam_videosearch_protocol_Head_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_casia_isiteam_videosearch_protocol_Context_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_casia_isiteam_videosearch_protocol_Context_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_casia_isiteam_videosearch_protocol_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_casia_isiteam_videosearch_protocol_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5casia/isiteam/videosearch/protocol/req" +
      "uestProto.proto\022\"casia.isiteam.videosear" +
      "ch.protocol\"J\n\004Head\022B\n\nmethodType\030\001 \002(\0162" +
      "..casia.isiteam.videosearch.protocol.Met" +
      "hodType\"\032\n\007Context\022\017\n\007context\030\001 \002(\t\"\177\n\007R" +
      "equest\0226\n\004head\030\001 \002(\0132(.casia.isiteam.vid" +
      "eosearch.protocol.Head\022<\n\007context\030\002 \002(\0132" +
      "+.casia.isiteam.videosearch.protocol.Con" +
      "text*?\n\nMethodType\022\r\n\tADD_VIDEO\020\001\022\020\n\014SEA" +
      "RCH_VIDEO\020\002\022\020\n\014DELETE_VIDEO\020\003B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_casia_isiteam_videosearch_protocol_Head_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_casia_isiteam_videosearch_protocol_Head_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_casia_isiteam_videosearch_protocol_Head_descriptor,
        new java.lang.String[] { "MethodType", });
    internal_static_casia_isiteam_videosearch_protocol_Context_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_casia_isiteam_videosearch_protocol_Context_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_casia_isiteam_videosearch_protocol_Context_descriptor,
        new java.lang.String[] { "Context", });
    internal_static_casia_isiteam_videosearch_protocol_Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_casia_isiteam_videosearch_protocol_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_casia_isiteam_videosearch_protocol_Request_descriptor,
        new java.lang.String[] { "Head", "Context", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
