// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: casia/isiteam/videosearch/protocol/responseProto.proto

package casia.isiteam.videosearch.protocol;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code casia.isiteam.videosearch.protocol.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 200;</code>
     */
    OK(0, 200),
    /**
     * <code>FAILED = 400;</code>
     */
    FAILED(1, 400),
    ;

    /**
     * <code>OK = 200;</code>
     */
    public static final int OK_VALUE = 200;
    /**
     * <code>FAILED = 400;</code>
     */
    public static final int FAILED_VALUE = 400;


    public final int getNumber() { return value; }

    public static Status valueOf(int value) {
      switch (value) {
        case 200: return OK;
        case 400: return FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return casia.isiteam.videosearch.protocol.ResponseProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Status(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:casia.isiteam.videosearch.protocol.Status)
  }

  public interface HeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:casia.isiteam.videosearch.protocol.Head)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .casia.isiteam.videosearch.protocol.Status status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Status status = 1;</code>
     */
    casia.isiteam.videosearch.protocol.ResponseProto.Status getStatus();
  }
  /**
   * Protobuf type {@code casia.isiteam.videosearch.protocol.Head}
   */
  public static final class Head extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:casia.isiteam.videosearch.protocol.Head)
      HeadOrBuilder {
    // Use Head.newBuilder() to construct.
    private Head(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Head(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Head defaultInstance;
    public static Head getDefaultInstance() {
      return defaultInstance;
    }

    public Head getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Head(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              casia.isiteam.videosearch.protocol.ResponseProto.Status value = casia.isiteam.videosearch.protocol.ResponseProto.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Head_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Head_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              casia.isiteam.videosearch.protocol.ResponseProto.Head.class, casia.isiteam.videosearch.protocol.ResponseProto.Head.Builder.class);
    }

    public static com.google.protobuf.Parser<Head> PARSER =
        new com.google.protobuf.AbstractParser<Head>() {
      public Head parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Head(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Head> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private casia.isiteam.videosearch.protocol.ResponseProto.Status status_;
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Status status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Status status = 1;</code>
     */
    public casia.isiteam.videosearch.protocol.ResponseProto.Status getStatus() {
      return status_;
    }

    private void initFields() {
      status_ = casia.isiteam.videosearch.protocol.ResponseProto.Status.OK;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static casia.isiteam.videosearch.protocol.ResponseProto.Head parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Head parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Head parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Head parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Head parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Head parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Head parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Head parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Head parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Head parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(casia.isiteam.videosearch.protocol.ResponseProto.Head prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code casia.isiteam.videosearch.protocol.Head}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:casia.isiteam.videosearch.protocol.Head)
        casia.isiteam.videosearch.protocol.ResponseProto.HeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Head_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Head_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                casia.isiteam.videosearch.protocol.ResponseProto.Head.class, casia.isiteam.videosearch.protocol.ResponseProto.Head.Builder.class);
      }

      // Construct using casia.isiteam.videosearch.protocol.ResponseProto.Head.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = casia.isiteam.videosearch.protocol.ResponseProto.Status.OK;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Head_descriptor;
      }

      public casia.isiteam.videosearch.protocol.ResponseProto.Head getDefaultInstanceForType() {
        return casia.isiteam.videosearch.protocol.ResponseProto.Head.getDefaultInstance();
      }

      public casia.isiteam.videosearch.protocol.ResponseProto.Head build() {
        casia.isiteam.videosearch.protocol.ResponseProto.Head result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public casia.isiteam.videosearch.protocol.ResponseProto.Head buildPartial() {
        casia.isiteam.videosearch.protocol.ResponseProto.Head result = new casia.isiteam.videosearch.protocol.ResponseProto.Head(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof casia.isiteam.videosearch.protocol.ResponseProto.Head) {
          return mergeFrom((casia.isiteam.videosearch.protocol.ResponseProto.Head)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(casia.isiteam.videosearch.protocol.ResponseProto.Head other) {
        if (other == casia.isiteam.videosearch.protocol.ResponseProto.Head.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        casia.isiteam.videosearch.protocol.ResponseProto.Head parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (casia.isiteam.videosearch.protocol.ResponseProto.Head) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private casia.isiteam.videosearch.protocol.ResponseProto.Status status_ = casia.isiteam.videosearch.protocol.ResponseProto.Status.OK;
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Status status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Status status = 1;</code>
       */
      public casia.isiteam.videosearch.protocol.ResponseProto.Status getStatus() {
        return status_;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Status status = 1;</code>
       */
      public Builder setStatus(casia.isiteam.videosearch.protocol.ResponseProto.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Status status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = casia.isiteam.videosearch.protocol.ResponseProto.Status.OK;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:casia.isiteam.videosearch.protocol.Head)
    }

    static {
      defaultInstance = new Head(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:casia.isiteam.videosearch.protocol.Head)
  }

  public interface ContextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:casia.isiteam.videosearch.protocol.Context)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string context = 1;</code>
     */
    boolean hasContext();
    /**
     * <code>required string context = 1;</code>
     */
    java.lang.String getContext();
    /**
     * <code>required string context = 1;</code>
     */
    com.google.protobuf.ByteString
        getContextBytes();
  }
  /**
   * Protobuf type {@code casia.isiteam.videosearch.protocol.Context}
   */
  public static final class Context extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:casia.isiteam.videosearch.protocol.Context)
      ContextOrBuilder {
    // Use Context.newBuilder() to construct.
    private Context(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Context(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Context defaultInstance;
    public static Context getDefaultInstance() {
      return defaultInstance;
    }

    public Context getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Context(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              context_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Context_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Context_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              casia.isiteam.videosearch.protocol.ResponseProto.Context.class, casia.isiteam.videosearch.protocol.ResponseProto.Context.Builder.class);
    }

    public static com.google.protobuf.Parser<Context> PARSER =
        new com.google.protobuf.AbstractParser<Context>() {
      public Context parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Context(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Context> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CONTEXT_FIELD_NUMBER = 1;
    private java.lang.Object context_;
    /**
     * <code>required string context = 1;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string context = 1;</code>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string context = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      context_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static casia.isiteam.videosearch.protocol.ResponseProto.Context parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Context parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Context parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Context parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Context parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Context parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Context parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Context parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Context parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Context parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(casia.isiteam.videosearch.protocol.ResponseProto.Context prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code casia.isiteam.videosearch.protocol.Context}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:casia.isiteam.videosearch.protocol.Context)
        casia.isiteam.videosearch.protocol.ResponseProto.ContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Context_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Context_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                casia.isiteam.videosearch.protocol.ResponseProto.Context.class, casia.isiteam.videosearch.protocol.ResponseProto.Context.Builder.class);
      }

      // Construct using casia.isiteam.videosearch.protocol.ResponseProto.Context.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Context_descriptor;
      }

      public casia.isiteam.videosearch.protocol.ResponseProto.Context getDefaultInstanceForType() {
        return casia.isiteam.videosearch.protocol.ResponseProto.Context.getDefaultInstance();
      }

      public casia.isiteam.videosearch.protocol.ResponseProto.Context build() {
        casia.isiteam.videosearch.protocol.ResponseProto.Context result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public casia.isiteam.videosearch.protocol.ResponseProto.Context buildPartial() {
        casia.isiteam.videosearch.protocol.ResponseProto.Context result = new casia.isiteam.videosearch.protocol.ResponseProto.Context(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.context_ = context_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof casia.isiteam.videosearch.protocol.ResponseProto.Context) {
          return mergeFrom((casia.isiteam.videosearch.protocol.ResponseProto.Context)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(casia.isiteam.videosearch.protocol.ResponseProto.Context other) {
        if (other == casia.isiteam.videosearch.protocol.ResponseProto.Context.getDefaultInstance()) return this;
        if (other.hasContext()) {
          bitField0_ |= 0x00000001;
          context_ = other.context_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContext()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        casia.isiteam.videosearch.protocol.ResponseProto.Context parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (casia.isiteam.videosearch.protocol.ResponseProto.Context) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object context_ = "";
      /**
       * <code>required string context = 1;</code>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string context = 1;</code>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            context_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder setContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:casia.isiteam.videosearch.protocol.Context)
    }

    static {
      defaultInstance = new Context(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:casia.isiteam.videosearch.protocol.Context)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:casia.isiteam.videosearch.protocol.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    boolean hasHead();
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    casia.isiteam.videosearch.protocol.ResponseProto.Head getHead();
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    casia.isiteam.videosearch.protocol.ResponseProto.HeadOrBuilder getHeadOrBuilder();

    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    boolean hasContext();
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    casia.isiteam.videosearch.protocol.ResponseProto.Context getContext();
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    casia.isiteam.videosearch.protocol.ResponseProto.ContextOrBuilder getContextOrBuilder();
  }
  /**
   * Protobuf type {@code casia.isiteam.videosearch.protocol.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:casia.isiteam.videosearch.protocol.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              casia.isiteam.videosearch.protocol.ResponseProto.Head.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = head_.toBuilder();
              }
              head_ = input.readMessage(casia.isiteam.videosearch.protocol.ResponseProto.Head.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(head_);
                head_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              casia.isiteam.videosearch.protocol.ResponseProto.Context.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = context_.toBuilder();
              }
              context_ = input.readMessage(casia.isiteam.videosearch.protocol.ResponseProto.Context.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(context_);
                context_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              casia.isiteam.videosearch.protocol.ResponseProto.Response.class, casia.isiteam.videosearch.protocol.ResponseProto.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEAD_FIELD_NUMBER = 1;
    private casia.isiteam.videosearch.protocol.ResponseProto.Head head_;
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    public boolean hasHead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    public casia.isiteam.videosearch.protocol.ResponseProto.Head getHead() {
      return head_;
    }
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
     */
    public casia.isiteam.videosearch.protocol.ResponseProto.HeadOrBuilder getHeadOrBuilder() {
      return head_;
    }

    public static final int CONTEXT_FIELD_NUMBER = 2;
    private casia.isiteam.videosearch.protocol.ResponseProto.Context context_;
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    public casia.isiteam.videosearch.protocol.ResponseProto.Context getContext() {
      return context_;
    }
    /**
     * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
     */
    public casia.isiteam.videosearch.protocol.ResponseProto.ContextOrBuilder getContextOrBuilder() {
      return context_;
    }

    private void initFields() {
      head_ = casia.isiteam.videosearch.protocol.ResponseProto.Head.getDefaultInstance();
      context_ = casia.isiteam.videosearch.protocol.ResponseProto.Context.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHead().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getContext().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, context_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, context_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static casia.isiteam.videosearch.protocol.ResponseProto.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.ResponseProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(casia.isiteam.videosearch.protocol.ResponseProto.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code casia.isiteam.videosearch.protocol.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:casia.isiteam.videosearch.protocol.Response)
        casia.isiteam.videosearch.protocol.ResponseProto.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                casia.isiteam.videosearch.protocol.ResponseProto.Response.class, casia.isiteam.videosearch.protocol.ResponseProto.Response.Builder.class);
      }

      // Construct using casia.isiteam.videosearch.protocol.ResponseProto.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeadFieldBuilder();
          getContextFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headBuilder_ == null) {
          head_ = casia.isiteam.videosearch.protocol.ResponseProto.Head.getDefaultInstance();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (contextBuilder_ == null) {
          context_ = casia.isiteam.videosearch.protocol.ResponseProto.Context.getDefaultInstance();
        } else {
          contextBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return casia.isiteam.videosearch.protocol.ResponseProto.internal_static_casia_isiteam_videosearch_protocol_Response_descriptor;
      }

      public casia.isiteam.videosearch.protocol.ResponseProto.Response getDefaultInstanceForType() {
        return casia.isiteam.videosearch.protocol.ResponseProto.Response.getDefaultInstance();
      }

      public casia.isiteam.videosearch.protocol.ResponseProto.Response build() {
        casia.isiteam.videosearch.protocol.ResponseProto.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public casia.isiteam.videosearch.protocol.ResponseProto.Response buildPartial() {
        casia.isiteam.videosearch.protocol.ResponseProto.Response result = new casia.isiteam.videosearch.protocol.ResponseProto.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headBuilder_ == null) {
          result.head_ = head_;
        } else {
          result.head_ = headBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (contextBuilder_ == null) {
          result.context_ = context_;
        } else {
          result.context_ = contextBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof casia.isiteam.videosearch.protocol.ResponseProto.Response) {
          return mergeFrom((casia.isiteam.videosearch.protocol.ResponseProto.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(casia.isiteam.videosearch.protocol.ResponseProto.Response other) {
        if (other == casia.isiteam.videosearch.protocol.ResponseProto.Response.getDefaultInstance()) return this;
        if (other.hasHead()) {
          mergeHead(other.getHead());
        }
        if (other.hasContext()) {
          mergeContext(other.getContext());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHead()) {
          
          return false;
        }
        if (!hasContext()) {
          
          return false;
        }
        if (!getHead().isInitialized()) {
          
          return false;
        }
        if (!getContext().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        casia.isiteam.videosearch.protocol.ResponseProto.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (casia.isiteam.videosearch.protocol.ResponseProto.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private casia.isiteam.videosearch.protocol.ResponseProto.Head head_ = casia.isiteam.videosearch.protocol.ResponseProto.Head.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          casia.isiteam.videosearch.protocol.ResponseProto.Head, casia.isiteam.videosearch.protocol.ResponseProto.Head.Builder, casia.isiteam.videosearch.protocol.ResponseProto.HeadOrBuilder> headBuilder_;
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public boolean hasHead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public casia.isiteam.videosearch.protocol.ResponseProto.Head getHead() {
        if (headBuilder_ == null) {
          return head_;
        } else {
          return headBuilder_.getMessage();
        }
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public Builder setHead(casia.isiteam.videosearch.protocol.ResponseProto.Head value) {
        if (headBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          head_ = value;
          onChanged();
        } else {
          headBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public Builder setHead(
          casia.isiteam.videosearch.protocol.ResponseProto.Head.Builder builderForValue) {
        if (headBuilder_ == null) {
          head_ = builderForValue.build();
          onChanged();
        } else {
          headBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public Builder mergeHead(casia.isiteam.videosearch.protocol.ResponseProto.Head value) {
        if (headBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              head_ != casia.isiteam.videosearch.protocol.ResponseProto.Head.getDefaultInstance()) {
            head_ =
              casia.isiteam.videosearch.protocol.ResponseProto.Head.newBuilder(head_).mergeFrom(value).buildPartial();
          } else {
            head_ = value;
          }
          onChanged();
        } else {
          headBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public Builder clearHead() {
        if (headBuilder_ == null) {
          head_ = casia.isiteam.videosearch.protocol.ResponseProto.Head.getDefaultInstance();
          onChanged();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public casia.isiteam.videosearch.protocol.ResponseProto.Head.Builder getHeadBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeadFieldBuilder().getBuilder();
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      public casia.isiteam.videosearch.protocol.ResponseProto.HeadOrBuilder getHeadOrBuilder() {
        if (headBuilder_ != null) {
          return headBuilder_.getMessageOrBuilder();
        } else {
          return head_;
        }
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Head head = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          casia.isiteam.videosearch.protocol.ResponseProto.Head, casia.isiteam.videosearch.protocol.ResponseProto.Head.Builder, casia.isiteam.videosearch.protocol.ResponseProto.HeadOrBuilder> 
          getHeadFieldBuilder() {
        if (headBuilder_ == null) {
          headBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              casia.isiteam.videosearch.protocol.ResponseProto.Head, casia.isiteam.videosearch.protocol.ResponseProto.Head.Builder, casia.isiteam.videosearch.protocol.ResponseProto.HeadOrBuilder>(
                  getHead(),
                  getParentForChildren(),
                  isClean());
          head_ = null;
        }
        return headBuilder_;
      }

      private casia.isiteam.videosearch.protocol.ResponseProto.Context context_ = casia.isiteam.videosearch.protocol.ResponseProto.Context.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          casia.isiteam.videosearch.protocol.ResponseProto.Context, casia.isiteam.videosearch.protocol.ResponseProto.Context.Builder, casia.isiteam.videosearch.protocol.ResponseProto.ContextOrBuilder> contextBuilder_;
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public casia.isiteam.videosearch.protocol.ResponseProto.Context getContext() {
        if (contextBuilder_ == null) {
          return context_;
        } else {
          return contextBuilder_.getMessage();
        }
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public Builder setContext(casia.isiteam.videosearch.protocol.ResponseProto.Context value) {
        if (contextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          context_ = value;
          onChanged();
        } else {
          contextBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public Builder setContext(
          casia.isiteam.videosearch.protocol.ResponseProto.Context.Builder builderForValue) {
        if (contextBuilder_ == null) {
          context_ = builderForValue.build();
          onChanged();
        } else {
          contextBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public Builder mergeContext(casia.isiteam.videosearch.protocol.ResponseProto.Context value) {
        if (contextBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              context_ != casia.isiteam.videosearch.protocol.ResponseProto.Context.getDefaultInstance()) {
            context_ =
              casia.isiteam.videosearch.protocol.ResponseProto.Context.newBuilder(context_).mergeFrom(value).buildPartial();
          } else {
            context_ = value;
          }
          onChanged();
        } else {
          contextBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public Builder clearContext() {
        if (contextBuilder_ == null) {
          context_ = casia.isiteam.videosearch.protocol.ResponseProto.Context.getDefaultInstance();
          onChanged();
        } else {
          contextBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public casia.isiteam.videosearch.protocol.ResponseProto.Context.Builder getContextBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getContextFieldBuilder().getBuilder();
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      public casia.isiteam.videosearch.protocol.ResponseProto.ContextOrBuilder getContextOrBuilder() {
        if (contextBuilder_ != null) {
          return contextBuilder_.getMessageOrBuilder();
        } else {
          return context_;
        }
      }
      /**
       * <code>required .casia.isiteam.videosearch.protocol.Context context = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          casia.isiteam.videosearch.protocol.ResponseProto.Context, casia.isiteam.videosearch.protocol.ResponseProto.Context.Builder, casia.isiteam.videosearch.protocol.ResponseProto.ContextOrBuilder> 
          getContextFieldBuilder() {
        if (contextBuilder_ == null) {
          contextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              casia.isiteam.videosearch.protocol.ResponseProto.Context, casia.isiteam.videosearch.protocol.ResponseProto.Context.Builder, casia.isiteam.videosearch.protocol.ResponseProto.ContextOrBuilder>(
                  getContext(),
                  getParentForChildren(),
                  isClean());
          context_ = null;
        }
        return contextBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:casia.isiteam.videosearch.protocol.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:casia.isiteam.videosearch.protocol.Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_casia_isiteam_videosearch_protocol_Head_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_casia_isiteam_videosearch_protocol_Head_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_casia_isiteam_videosearch_protocol_Context_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_casia_isiteam_videosearch_protocol_Context_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_casia_isiteam_videosearch_protocol_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_casia_isiteam_videosearch_protocol_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6casia/isiteam/videosearch/protocol/res" +
      "ponseProto.proto\022\"casia.isiteam.videosea" +
      "rch.protocol\"B\n\004Head\022:\n\006status\030\001 \002(\0162*.c" +
      "asia.isiteam.videosearch.protocol.Status" +
      "\"\032\n\007Context\022\017\n\007context\030\001 \002(\t\"\200\001\n\010Respons" +
      "e\0226\n\004head\030\001 \002(\0132(.casia.isiteam.videosea" +
      "rch.protocol.Head\022<\n\007context\030\002 \002(\0132+.cas" +
      "ia.isiteam.videosearch.protocol.Context*" +
      "\036\n\006Status\022\007\n\002OK\020\310\001\022\013\n\006FAILED\020\220\003B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_casia_isiteam_videosearch_protocol_Head_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_casia_isiteam_videosearch_protocol_Head_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_casia_isiteam_videosearch_protocol_Head_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_casia_isiteam_videosearch_protocol_Context_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_casia_isiteam_videosearch_protocol_Context_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_casia_isiteam_videosearch_protocol_Context_descriptor,
        new java.lang.String[] { "Context", });
    internal_static_casia_isiteam_videosearch_protocol_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_casia_isiteam_videosearch_protocol_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_casia_isiteam_videosearch_protocol_Response_descriptor,
        new java.lang.String[] { "Head", "Context", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
