// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: casia/isiteam/videosearch/protocol/test.proto

package casia.isiteam.videosearch.protocol;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface M1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:casia.isiteam.videosearch.protocol.M1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string context = 1;</code>
     */
    boolean hasContext();
    /**
     * <code>required string context = 1;</code>
     */
    java.lang.String getContext();
    /**
     * <code>required string context = 1;</code>
     */
    com.google.protobuf.ByteString
        getContextBytes();
  }
  /**
   * Protobuf type {@code casia.isiteam.videosearch.protocol.M1}
   */
  public static final class M1 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:casia.isiteam.videosearch.protocol.M1)
      M1OrBuilder {
    // Use M1.newBuilder() to construct.
    private M1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private M1(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final M1 defaultInstance;
    public static M1 getDefaultInstance() {
      return defaultInstance;
    }

    public M1 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private M1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              context_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return casia.isiteam.videosearch.protocol.Test.internal_static_casia_isiteam_videosearch_protocol_M1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return casia.isiteam.videosearch.protocol.Test.internal_static_casia_isiteam_videosearch_protocol_M1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              casia.isiteam.videosearch.protocol.Test.M1.class, casia.isiteam.videosearch.protocol.Test.M1.Builder.class);
    }

    public static com.google.protobuf.Parser<M1> PARSER =
        new com.google.protobuf.AbstractParser<M1>() {
      public M1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new M1(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<M1> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CONTEXT_FIELD_NUMBER = 1;
    private java.lang.Object context_;
    /**
     * <code>required string context = 1;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string context = 1;</code>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string context = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      context_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static casia.isiteam.videosearch.protocol.Test.M1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.Test.M1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.Test.M1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.Test.M1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.Test.M1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.Test.M1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.Test.M1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.Test.M1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.Test.M1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.Test.M1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(casia.isiteam.videosearch.protocol.Test.M1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code casia.isiteam.videosearch.protocol.M1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:casia.isiteam.videosearch.protocol.M1)
        casia.isiteam.videosearch.protocol.Test.M1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return casia.isiteam.videosearch.protocol.Test.internal_static_casia_isiteam_videosearch_protocol_M1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return casia.isiteam.videosearch.protocol.Test.internal_static_casia_isiteam_videosearch_protocol_M1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                casia.isiteam.videosearch.protocol.Test.M1.class, casia.isiteam.videosearch.protocol.Test.M1.Builder.class);
      }

      // Construct using casia.isiteam.videosearch.protocol.Test.M1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return casia.isiteam.videosearch.protocol.Test.internal_static_casia_isiteam_videosearch_protocol_M1_descriptor;
      }

      public casia.isiteam.videosearch.protocol.Test.M1 getDefaultInstanceForType() {
        return casia.isiteam.videosearch.protocol.Test.M1.getDefaultInstance();
      }

      public casia.isiteam.videosearch.protocol.Test.M1 build() {
        casia.isiteam.videosearch.protocol.Test.M1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public casia.isiteam.videosearch.protocol.Test.M1 buildPartial() {
        casia.isiteam.videosearch.protocol.Test.M1 result = new casia.isiteam.videosearch.protocol.Test.M1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.context_ = context_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof casia.isiteam.videosearch.protocol.Test.M1) {
          return mergeFrom((casia.isiteam.videosearch.protocol.Test.M1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(casia.isiteam.videosearch.protocol.Test.M1 other) {
        if (other == casia.isiteam.videosearch.protocol.Test.M1.getDefaultInstance()) return this;
        if (other.hasContext()) {
          bitField0_ |= 0x00000001;
          context_ = other.context_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContext()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        casia.isiteam.videosearch.protocol.Test.M1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (casia.isiteam.videosearch.protocol.Test.M1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object context_ = "";
      /**
       * <code>required string context = 1;</code>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string context = 1;</code>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            context_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder setContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:casia.isiteam.videosearch.protocol.M1)
    }

    static {
      defaultInstance = new M1(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:casia.isiteam.videosearch.protocol.M1)
  }

  public interface M2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:casia.isiteam.videosearch.protocol.M2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string context = 1;</code>
     */
    boolean hasContext();
    /**
     * <code>required string context = 1;</code>
     */
    java.lang.String getContext();
    /**
     * <code>required string context = 1;</code>
     */
    com.google.protobuf.ByteString
        getContextBytes();

    /**
     * <code>required string context2 = 2;</code>
     */
    boolean hasContext2();
    /**
     * <code>required string context2 = 2;</code>
     */
    java.lang.String getContext2();
    /**
     * <code>required string context2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getContext2Bytes();
  }
  /**
   * Protobuf type {@code casia.isiteam.videosearch.protocol.M2}
   */
  public static final class M2 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:casia.isiteam.videosearch.protocol.M2)
      M2OrBuilder {
    // Use M2.newBuilder() to construct.
    private M2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private M2(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final M2 defaultInstance;
    public static M2 getDefaultInstance() {
      return defaultInstance;
    }

    public M2 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private M2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              context_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              context2_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return casia.isiteam.videosearch.protocol.Test.internal_static_casia_isiteam_videosearch_protocol_M2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return casia.isiteam.videosearch.protocol.Test.internal_static_casia_isiteam_videosearch_protocol_M2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              casia.isiteam.videosearch.protocol.Test.M2.class, casia.isiteam.videosearch.protocol.Test.M2.Builder.class);
    }

    public static com.google.protobuf.Parser<M2> PARSER =
        new com.google.protobuf.AbstractParser<M2>() {
      public M2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new M2(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<M2> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CONTEXT_FIELD_NUMBER = 1;
    private java.lang.Object context_;
    /**
     * <code>required string context = 1;</code>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string context = 1;</code>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string context = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTEXT2_FIELD_NUMBER = 2;
    private java.lang.Object context2_;
    /**
     * <code>required string context2 = 2;</code>
     */
    public boolean hasContext2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string context2 = 2;</code>
     */
    public java.lang.String getContext2() {
      java.lang.Object ref = context2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string context2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContext2Bytes() {
      java.lang.Object ref = context2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      context_ = "";
      context2_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContext2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContext2Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContext2Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static casia.isiteam.videosearch.protocol.Test.M2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.Test.M2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.Test.M2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static casia.isiteam.videosearch.protocol.Test.M2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.Test.M2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.Test.M2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.Test.M2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.Test.M2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static casia.isiteam.videosearch.protocol.Test.M2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static casia.isiteam.videosearch.protocol.Test.M2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(casia.isiteam.videosearch.protocol.Test.M2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code casia.isiteam.videosearch.protocol.M2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:casia.isiteam.videosearch.protocol.M2)
        casia.isiteam.videosearch.protocol.Test.M2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return casia.isiteam.videosearch.protocol.Test.internal_static_casia_isiteam_videosearch_protocol_M2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return casia.isiteam.videosearch.protocol.Test.internal_static_casia_isiteam_videosearch_protocol_M2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                casia.isiteam.videosearch.protocol.Test.M2.class, casia.isiteam.videosearch.protocol.Test.M2.Builder.class);
      }

      // Construct using casia.isiteam.videosearch.protocol.Test.M2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        context2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return casia.isiteam.videosearch.protocol.Test.internal_static_casia_isiteam_videosearch_protocol_M2_descriptor;
      }

      public casia.isiteam.videosearch.protocol.Test.M2 getDefaultInstanceForType() {
        return casia.isiteam.videosearch.protocol.Test.M2.getDefaultInstance();
      }

      public casia.isiteam.videosearch.protocol.Test.M2 build() {
        casia.isiteam.videosearch.protocol.Test.M2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public casia.isiteam.videosearch.protocol.Test.M2 buildPartial() {
        casia.isiteam.videosearch.protocol.Test.M2 result = new casia.isiteam.videosearch.protocol.Test.M2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.context_ = context_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.context2_ = context2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof casia.isiteam.videosearch.protocol.Test.M2) {
          return mergeFrom((casia.isiteam.videosearch.protocol.Test.M2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(casia.isiteam.videosearch.protocol.Test.M2 other) {
        if (other == casia.isiteam.videosearch.protocol.Test.M2.getDefaultInstance()) return this;
        if (other.hasContext()) {
          bitField0_ |= 0x00000001;
          context_ = other.context_;
          onChanged();
        }
        if (other.hasContext2()) {
          bitField0_ |= 0x00000002;
          context2_ = other.context2_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContext()) {
          
          return false;
        }
        if (!hasContext2()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        casia.isiteam.videosearch.protocol.Test.M2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (casia.isiteam.videosearch.protocol.Test.M2) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object context_ = "";
      /**
       * <code>required string context = 1;</code>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string context = 1;</code>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            context_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder setContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object context2_ = "";
      /**
       * <code>required string context2 = 2;</code>
       */
      public boolean hasContext2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string context2 = 2;</code>
       */
      public java.lang.String getContext2() {
        java.lang.Object ref = context2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            context2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string context2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContext2Bytes() {
        java.lang.Object ref = context2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string context2 = 2;</code>
       */
      public Builder setContext2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        context2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string context2 = 2;</code>
       */
      public Builder clearContext2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        context2_ = getDefaultInstance().getContext2();
        onChanged();
        return this;
      }
      /**
       * <code>required string context2 = 2;</code>
       */
      public Builder setContext2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        context2_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:casia.isiteam.videosearch.protocol.M2)
    }

    static {
      defaultInstance = new M2(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:casia.isiteam.videosearch.protocol.M2)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_casia_isiteam_videosearch_protocol_M1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_casia_isiteam_videosearch_protocol_M1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_casia_isiteam_videosearch_protocol_M2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_casia_isiteam_videosearch_protocol_M2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-casia/isiteam/videosearch/protocol/tes" +
      "t.proto\022\"casia.isiteam.videosearch.proto" +
      "col\"\025\n\002M1\022\017\n\007context\030\001 \002(\t\"\'\n\002M2\022\017\n\007cont" +
      "ext\030\001 \002(\t\022\020\n\010context2\030\002 \002(\tB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_casia_isiteam_videosearch_protocol_M1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_casia_isiteam_videosearch_protocol_M1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_casia_isiteam_videosearch_protocol_M1_descriptor,
        new java.lang.String[] { "Context", });
    internal_static_casia_isiteam_videosearch_protocol_M2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_casia_isiteam_videosearch_protocol_M2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_casia_isiteam_videosearch_protocol_M2_descriptor,
        new java.lang.String[] { "Context", "Context2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
